name: Create AWS infrastructure

on:
  workflow_dispatch:

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_id: ${{ steps.binary-upload-step.outputs.artifact-id }}

    steps:
    - uses: actions/checkout@v4
                    
    - uses: hashicorp/setup-terraform@v2
    
    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=$BUCKET_TF_STATE" -backend-config="region=${{vars.AWS_REGION}}"
 
    - name: Terraform format
      id: fmt
      run: terraform fmt -check
    
    - name: Terraform validate
      id: validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
